# Generated by Django 5.0.14 on 2026-06-10 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(help_text='Instructions/Plan added by Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visit_plans', to=settings.AUTH_USER_MODEL)),
                ('sales_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'permissions': [('view_weekly_summary', 'Can view weekly summary report')],
                'unique_together': {('date', 'sales_officer')},
            },
        ),
        migrations.CreateModel(
            name='VisitTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_done', models.TextField(blank=True, help_text='Tasks actually completed', null=True)),
                ('remarks', models.TextField(blank=True, help_text="Sales Officer's remarks after visit", null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='visits.visitplan')),
            ],
        ),
    ]
