# Generated by Django 5.0.14 on 2026-06-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitplan',
            unique_together=set(),
        ),
    ]
