# Generated by Django 5.0.14 on 2026-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_label', models.CharField(help_text="e.g. 'crm', 'inventory', 'sales'", max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='accessible_modules',
            field=models.ManyToManyField(blank=True, to='users.appmodule'),
        ),
    ]
