# Generated by Django 5.0.14 on 2026-03-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appmodule_user_accessible_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accessible_modules',
        ),
        migrations.DeleteModel(
            name='AppModule',
        ),
    ]
