# Generated by Django 5.0.14 on 2026-04-06 05:09

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_managers(apps, schema_editor):
    User = apps.get_model('users', 'User')
    
    managers = [
        {'username': 'admin', 'email': 'admin@organicfoodslanka.com'},
        {'username': 'hashan', 'email': 'hashan@organicfoodslanka.com'}
    ]
    
    for mgr in managers:
        if not User.objects.filter(username=mgr['username']).exists():
            User.objects.create(
                username=mgr['username'],
                email=mgr['email'],
                password=make_password('admin1234'),
                is_superuser=True,
                role='ADMIN'
            )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_accessible_modules_delete_appmodule'),
    ]

    operations = [
        migrations.RunPython(create_managers),
    ]
