# Generated by Django 5.0.14 on 2026-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_savedfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES_OFFICER', 'Sales Officer'), ('NORMAL_USER', 'Normal User')], default='SALES_OFFICER', max_length=50),
        ),
    ]
