# Generated by Django 5.0.14 on 2026-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES_OFFICER', 'Sales Officer'), ('USER', 'User')], default='SALES_OFFICER', max_length=50),
        ),
    ]
