# Generated by Django 5.0.14 on 2026-05-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery_officer',
            field=models.BooleanField(default=False, verbose_name='Is a Delivery Officer?'),
        ),
    ]
