# Generated by Django 5.0.14 on 2026-05-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_delivery_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_delivery_officer',
            field=models.BooleanField(default=False, help_text='User can be assigned to deliver orders.', verbose_name='Is a Delivery Officer?'),
        ),
    ]
