# Generated by Django 5.0.14 on 2026-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_is_delivery_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly sales target (Ex-VAT) for this officer.', max_digits=12),
        ),
    ]
