# Generated by Django 5.0.14 on 2026-05-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_monthly_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_set_targets',
            field=models.BooleanField(default=False, help_text='Allow this user to access the Analytics Target Management page.', verbose_name='Can Set Sales Targets?'),
        ),
    ]
