# Generated by Django 5.0.14 on 2026-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_role_fk_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_approve_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_reject_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('approval_required', 'Approval Required')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_email_alerts',
            field=models.BooleanField(default=True, help_text='Receive email notifications for approvals and alerts.', verbose_name='Receive Email Alerts'),
        ),
    ]
