# Generated by Django 5.0.14 on 2026-06-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification_action_approve_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_all_sales_performance',
            field=models.BooleanField(default=False, help_text="Allow this user to view other sales officers' performance in the analytics dashboard.", verbose_name='Can View All Sales Performance?'),
        ),
    ]
