# Generated by Django 5.0.14 on 2026-04-20 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_type', models.CharField(choices=[('SUGAR', 'Sugar'), ('RAW_MATERIAL', 'Raw material supplier'), ('TEA_RAW', 'Tea raw supplier'), ('PRINTING_SERVICE', 'Printing service supplier'), ('PACKING_SERVICE', 'Packing service supplier'), ('DRIED_RAW', 'Dried raw material supplier'), ('SPICES_RAW', 'Spices raw material supplier'), ('KITHUL', 'Kithul supplier'), ('HERBS_RAW', 'Herbs raw material supplier'), ('TRADING_ITEM', 'Trading item supplier'), ('OTHER', 'Other')], max_length=50)),
                ('custom_supplier_type', models.CharField(blank=True, help_text='Specify if type is Other', max_length=150, null=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Contact number must contain only digits.', regex='^\\d+$')])),
                ('email', models.EmailField(blank=True, help_text='Valid email, optionally provided', max_length=254, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_reg_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Registration Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
