# Generated by Django 5.0.14 on 2026-04-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line1',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='province',
            field=models.CharField(choices=[('WESTERN', 'Western Province'), ('CENTRAL', 'Central Province'), ('SOUTHERN', 'Southern Province'), ('UVA', 'Uva Province'), ('SABARAGAMUWA', 'Sabaragamuwa Province'), ('NORTH_WESTERN', 'North Western Province'), ('NORTH_CENTRAL', 'North Central Province'), ('NORTHERN', 'Northern Province'), ('EASTERN', 'Eastern Province')], default='WESTERN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('BOC', 'Bank of Ceylon (BOC)'), ('PEOPLES', "People's Bank"), ('COMMERCIAL', 'Commercial Bank of Ceylon PLC'), ('HNB', 'Hatton National Bank PLC (HNB)'), ('SAMPATH', 'Sampath Bank PLC'), ('SEYLAN', 'Seylan Bank PLC'), ('NTB', 'Nations Trust Bank PLC (NTB)'), ('NDB', 'National Development Bank PLC (NDB)'), ('DFCC', 'DFCC Bank PLC'), ('PAN_ASIA', 'Pan Asia Banking Corporation PLC'), ('UNION', 'Union Bank of Colombo PLC'), ('STANDARD_CHARTERED', 'Standard Chartered Bank'), ('HSBC', 'HSBC'), ('AMANA', 'Amana Bank'), ('CARGILLS', 'Cargills Bank')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_reg_num',
            field=models.CharField(blank=True, help_text='Enter valid VAT number', max_length=50, null=True, verbose_name='VAT Registration Number'),
        ),
    ]
