# Generated by Django 5.0.14 on 2026-05-12 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_supplier_address_supplier_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='alternate_contact_number',
            field=models.CharField(blank=True, help_text='Optional secondary contact number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
