# Generated by Django 5.0.14 on 2026-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_product_estimated_weight_kg'),
        ('suppliers', '0003_supplier_alternate_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select the products this supplier can provide', related_name='suppliers', to='inventory.product'),
        ),
    ]
