server {
    server_name erp.organicfoodslanka.com 178.128.52.97;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /var/www/everbolt-erp/staticfiles/;
    }

    location /media/ {
        alias /var/www/everbolt-erp/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/erp.organicfoodslanka.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/erp.organicfoodslanka.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    server_name organicfoodslanka.com www.organicfoodslanka.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /var/www/everbolt-erp/staticfiles/;
    }

    location /media/ {
        alias /var/www/everbolt-erp/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/organicfoodslanka.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/organicfoodslanka.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.organicfoodslanka.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = organicfoodslanka.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = erp.organicfoodslanka.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name erp.organicfoodslanka.com organicfoodslanka.com www.organicfoodslanka.com 178.128.52.97;
    return 404; # managed by Certbot
}
