# Generated by Django 5.0.14 on 2026-06-18 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_reorder_notified'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_order_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(default='COD', max_length=50)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted to Sales Order/Invoice'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='about_section',
            field=models.JSONField(blank=True, default=dict, help_text='JSON containing title, subtitle, description, button_text, button_url, image'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='cta_section',
            field=models.JSONField(blank=True, default=dict, help_text='JSON containing title, description, button_text, button_url'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='hero_section',
            field=models.JSONField(blank=True, default=dict, help_text='JSON containing title, description, and slides array'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='why_choose_us_section',
            field=models.JSONField(blank=True, default=dict, help_text='JSON containing title, description, and features array'),
        ),
        migrations.CreateModel(
            name='WebsiteOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.websiteorder')),
                ('website_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.websiteproduct')),
            ],
        ),
    ]
