# Generated by Django 5.0.14 on 2026-06-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websiteorder_websitesettings_about_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproduct',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Primary image for the website', null=True, upload_to='website/products/'),
        ),
    ]
