# Generated by Django 5.0.14 on 2026-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_websiteblogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Category cover image', null=True, upload_to='website/categories/'),
        ),
    ]
