# Generated by Django

from django.db import migrations
from django.utils.text import slugify

def seed_categories(apps, schema_editor):
    WebsiteCategory = apps.get_model('website', 'WebsiteCategory')
    
    categories = [
        {'name': 'Flavoured Tea', 'display_order': 10},
        {'name': 'Herbal Tea', 'display_order': 20},
        {'name': 'Premium Spices', 'display_order': 30},
        {'name': 'Everleaf Range', 'display_order': 40},
        {'name': 'Kithul Products', 'display_order': 50},
        {'name': 'Hotel Supplies', 'display_order': 60},
    ]

    for cat_data in categories:
        if not WebsiteCategory.objects.filter(name=cat_data['name']).exists():
            WebsiteCategory.objects.create(
                name=cat_data['name'],
                slug=slugify(cat_data['name']),
                display_order=cat_data['display_order'],
                is_visible=True
            )

def reverse_categories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_websitecategory_image'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_categories),
    ]
