# Generated by Django 5.0.14 on 2026-06-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_seed_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional heading for this slide', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Optional subheading for this slide')),
                ('image', models.ImageField(help_text='High-res hero background image', upload_to='website/hero/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
