# Generated by Django 5.0.14 on 2026-06-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_seed_default_hero_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEORedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Old URL path (e.g., /category/spices/)', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='New URL path (e.g., /shop/category/spices/)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Redirect',
                'verbose_name_plural': 'SEO Redirects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='websitecategory',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Main keyword for SEO', max_length=150),
        ),
        migrations.AddField(
            model_name='websitecategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description'),
        ),
        migrations.AddField(
            model_name='websitecategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (overrides default)', max_length=200),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Main keyword for SEO', max_length=150),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (overrides default)', max_length=200),
        ),
        migrations.AddField(
            model_name='websiteproduct',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Main keyword for SEO', max_length=150),
        ),
        migrations.AddField(
            model_name='websiteproduct',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the main image', max_length=150),
        ),
        migrations.AddField(
            model_name='websiteproduct',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description'),
        ),
        migrations.AddField(
            model_name='websiteproduct',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (overrides default)', max_length=200),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description'),
        ),
    ]
