# Generated by Django 5.0.14 on 2026-06-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_seoredirect_websitecategory_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='order_notification_emails',
            field=models.CharField(default='info@organicfoodslanka.com, hashan@organicfoodslanka.com', help_text='Comma-separated emails to receive new order alerts', max_length=255),
        ),
    ]
