# Generated by Django 5.0.14 on 2026-06-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_websiteorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteorder',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted to Sales Invoice'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
