# Generated by Django 5.0.14 on 2026-06-24 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_product_estimated_weight_kg'),
        ('website', '0012_alter_websiteorder_sync_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text='E.g., 5g, 7g, 100g', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('inventory_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_variant_listing', to='inventory.product')),
                ('website_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='website.websiteproduct')),
            ],
            options={
                'verbose_name': 'Website Product Variant',
                'verbose_name_plural': 'Website Product Variants',
                'ordering': ['display_order', 'variant_name'],
            },
        ),
    ]
