# Generated by Django 5.0.14 on 2026-08-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_websiteproductvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteorder',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
