# Generated by Django 5.0.14 on 2026-06-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_populate_standard_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_finance', 'Can access the finance module'), ('post_journal_entry', 'Can post journal entries')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
    ]
