# Generated by Django 5.0.14 on 2026-07-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financemodule_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slip_attachment',
            field=models.FileField(blank=True, help_text='Image or PDF of the payment slip', null=True, upload_to='payment_slips/'),
        ),
    ]
