# Generated by Django 5.0.14 on 2026-07-09 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_migrate_legacy_delivery_addresses'),
        ('finance', '0006_payment_amount_decimal_precision'),
        ('sales', '0030_alter_deliverynote_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Reason for credit (e.g. Overpayment on Invoice #1023)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='sales.invoice')),
                ('customer_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='finance.customercredit')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
