# Generated by Django 5.0.14 on 2026-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_bankaccount_payment_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Credit/Debit Card'), ('CREDIT_NOTE', 'Credit Note'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20),
        ),
    ]
