# Generated by Django 5.0.14 on 2026-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='apply_vat',
            field=models.BooleanField(default=False, help_text='Apply 18% VAT'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='attention',
            field=models.CharField(blank=True, help_text='Contact person', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_term',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('CASH', 'Cash'), ('ADVANCE', 'Advance')], default='CREDIT', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
