# Generated by Django 5.0.14 on 2026-04-21 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseorder_apply_vat_purchaseorder_attention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_receipts', to='purchases.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_qty',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
