# Generated by Django 5.0.14 on 2026-05-13 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_grn_po_grnitem_po_item_and_more'),
        ('suppliers', '0003_supplier_alternate_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='supplier_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='supplier',
            field=models.CharField(blank=True, help_text='Legacy text snapshot — do not edit manually', max_length=200),
        ),
    ]
