# Generated by Django 5.0.14 on 2026-07-03 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_product_estimated_weight_kg'),
        ('purchases', '0006_backfill_grn_supplier_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='material_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
