# Generated by Django 5.0.14 on 2026-03-25 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year for the target (e.g., 2026)')),
                ('target_type', models.CharField(choices=[('OVERALL_SALES', 'Overall Sales'), ('CATEGORY_SALES', 'Category Sales'), ('CATEGORY_QTY', 'Category Quantity')], default='OVERALL_SALES', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Yearly target value', max_digits=14)),
                ('category', models.ForeignKey(blank=True, help_text='Select a category if target type is Category Sales or Category Qty', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
            options={
                'unique_together': {('year', 'target_type', 'category')},
            },
        ),
    ]
