# Generated by Django 5.0.14 on 2026-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestarget',
            name='category',
            field=models.CharField(blank=True, choices=[('Confectionery', 'Confectionery'), ('Dried Fruits', 'Dried Fruits'), ('Dried Vegetables', 'Dried Vegetables'), ('Spices', 'Spices'), ('Tea', 'Tea'), ('Kithul', 'Kithul')], help_text='Select a category if target type is Category Sales or Category Qty', max_length=50, null=True),
        ),
    ]
