# Generated by Django 5.0.14 on 2026-05-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_salestarget_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salestarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='month',
            field=models.IntegerField(blank=True, help_text='Leave blank for a yearly target. Set 1–12 for a specific month (1=Jan, 12=Dec).', null=True),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='target_value',
            field=models.DecimalField(decimal_places=2, help_text='Target value', max_digits=14),
        ),
        migrations.AlterUniqueTogether(
            name='salestarget',
            unique_together={('year', 'month', 'target_type', 'category')},
        ),
    ]
