# Generated by Django 5.0.14 on 2026-05-20 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_salestarget_unique_together_salestarget_month_and_more'),
        ('inventory', '0013_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestarget',
            name='category',
            field=models.CharField(blank=True, choices=[('Confectionery', 'Confectionery'), ('Dried Fruits', 'Dried Fruits'), ('Dried Vegetables', 'Dried Vegetables'), ('Spices', 'Spices'), ('Tea', 'Tea'), ('Kithul', 'Kithul')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='target_value',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.CreateModel(
            name='TrackedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='inventory.product')),
            ],
            options={
                'ordering': ['display_order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_targets', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'year', 'month')},
            },
        ),
    ]
