# Generated by Django 5.0.14 on 2026-05-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_initial_tracked_products'),
        ('inventory', '0013_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttarget',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_targets', to='inventory.product'),
        ),
        migrations.CreateModel(
            name='ProductTargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sugar Sachets, Nescafe', max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='target_groups', to='inventory.product')),
            ],
            options={
                'ordering': ['display_order', 'added_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='producttarget',
            unique_together={('product', 'year', 'month')},
        ),
        migrations.AddField(
            model_name='producttarget',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='dashboard.producttargetgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='producttarget',
            unique_together={('product', 'year', 'month'), ('target_group', 'year', 'month')},
        ),
    ]
