# Generated by Django 5.0.14 on 2026-05-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_migrate_to_product_groups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttarget',
            unique_together={('target_group', 'year', 'month')},
        ),
        migrations.AlterField(
            model_name='producttarget',
            name='target_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='dashboard.producttargetgroup'),
        ),
        migrations.DeleteModel(
            name='TrackedProduct',
        ),
        migrations.RemoveField(
            model_name='producttarget',
            name='product',
        ),
    ]
