# Generated by Django 5.0.14 on 2026-06-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_salespersontarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('milestone_target', models.DecimalField(decimal_places=2, default=500000, help_text='e.g., 500000 for 500k milestones', max_digits=14)),
                ('total_working_days', models.IntegerField(default=25, help_text='Total working days in the month (e.g., excluding Sundays and Poya)')),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
