# Generated by Django 5.0.14 on 2026-06-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_forecastingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Everbolt Food Products (Pvt) Ltd', max_length=200)),
                ('company_address', models.TextField(default='No.548/B Nawala Rd,\nSri Jayawardenepura Kotte 10100.')),
                ('telephone_number', models.CharField(default='076 540 0084', max_length=50)),
                ('tin_number', models.CharField(default='108438134', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
