# Generated by Django 5.0.14 on 2026-07-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='e.g. Everbolt Food Products (Pvt) Ltd', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='e.g. 92497445', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='e.g. Rajagiriya 746', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g. Bank of Ceylon (BOC)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Company email shown on printouts and emails.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_payment_modes',
            field=models.CharField(blank=True, default='Cash / Online / Direct Deposit / Cheque', help_text="Text shown after 'Mode of Payment:' on invoices and quotations.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_terms_and_conditions',
            field=models.TextField(blank=True, help_text='Custom Terms & Conditions for Invoice printouts. Each line will appear as a separate line.', null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='quotation_terms_and_conditions',
            field=models.TextField(blank=True, help_text='Custom Terms & Conditions for Quotation printouts. Each line will appear as a separate line.', null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='return_policy_days',
            field=models.PositiveIntegerField(default=5, help_text='Number of days within which returns are accepted.'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='website_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.yourcompany.com', null=True),
        ),
    ]
