# Generated by Django 5.0.14 on 2026-07-22 06:03

from django.db import migrations, models


def populate_payment_term_rules(apps, schema_editor):
    """Pre-populate the PaymentTermRule table with all 7 correct term rules."""
    PaymentTermRule = apps.get_model('dashboard', 'PaymentTermRule')
    rules = [
        # term_code, label, due_days, sort_order
        ('CASH',      'Cash',                0,  1),
        ('COD',       'Cash On Delivery',    15, 2),
        ('CREDIT_7',  'Credit - 7 days',     7,  3),
        ('CREDIT_15', 'Credit - 15 days',    15, 4),
        ('CREDIT_30', 'Credit - 30 days',    30, 5),
        ('CREDIT_45', 'Credit - 45 days',    45, 6),
        ('CREDIT_60', 'Credit - 60 days',    60, 7),
    ]
    for term_code, label, due_days, sort_order in rules:
        PaymentTermRule.objects.get_or_create(
            term_code=term_code,
            defaults={'label': label, 'due_days': due_days, 'is_active': True, 'sort_order': sort_order}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_companysettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTermRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_code', models.CharField(help_text='Machine key, e.g. CASH, COD, CREDIT_30', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Human-readable name shown in dropdowns', max_length=100)),
                ('due_days', models.IntegerField(default=0, help_text='Days from invoice creation date until payment is due. 0 = same day.')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive terms won't appear in the Customer payment terms dropdown.")),
                ('sort_order', models.IntegerField(default=0, help_text='Controls display order in dropdowns and the settings page.')),
            ],
            options={
                'verbose_name': 'Payment Term Rule',
                'verbose_name_plural': 'Payment Term Rules',
                'ordering': ['sort_order', 'term_code'],
            },
        ),
        migrations.RunPython(populate_payment_term_rules, migrations.RunPython.noop),
    ]
