# Generated by Django 5.0.14 on 2026-08-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_add_payment_term_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='invoice_number_format',
            field=models.CharField(default='{YY}{MMM}_EBFR_{SEQ}', help_text='Variables available: {YYYY}, {YY}, {MM}, {MMM}, {DD}, {SEQ}', max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='next_invoice_sequence',
            field=models.IntegerField(blank=True, help_text='If blank, the system automatically finds the highest number from existing invoices.', null=True),
        ),
    ]
