# Generated by Django 5.0.14 on 2026-03-17 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('packet_size', models.CharField(blank=True, max_length=100, null=True)),
                ('selling_unit', models.CharField(choices=[('PCS', 'pcs'), ('BOX', 'box'), ('PACK', 'pack'), ('KG', 'kg')], default='PCS', max_length=20)),
                ('product_type', models.CharField(choices=[('MANUFACTURED', 'Manufactured'), ('BLENDED', 'Blended'), ('REPACKED', 'Repacked'), ('CONTRACTED', 'Contracted Packing'), ('TRADING', 'Trading')], default='MANUFACTURED', max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('status', models.BooleanField(default=True, help_text='True if active/in stock')),
                ('current_stock', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
        ),
    ]
