# Generated by Django 5.0.14 on 2026-03-19 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_product_id_alter_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_class',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('PACKAGING', 'Packaging Material'), ('FINISHED', 'Finished Good'), ('SEMI_FINISHED', 'Semi-Finished Good'), ('CONSUMABLE', 'Consumable')], default='FINISHED', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_unit',
            field=models.CharField(choices=[('PCS', 'pcs'), ('BOX', 'box'), ('PACK', 'pack'), ('KG', 'kg'), ('G', 'g'), ('L', 'l'), ('ML', 'ml')], default='PCS', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Cached balance from StockLedger', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MANUFACTURED', 'Manufactured'), ('REPACKED', 'Repacked'), ('BLENDED', 'Blended'), ('TRADING', 'Trading'), ('CONTRACTED', 'Contract Packed')], default='MANUFACTURED', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('PCS', 'pcs'), ('BOX', 'box'), ('PACK', 'pack'), ('KG', 'kg'), ('G', 'g'), ('L', 'l'), ('ML', 'ml')], default='PCS', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, help_text='True if active'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tx_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('GRN', 'GRN'), ('PROD_CONS', 'Production Consumption'), ('PROD_OUT', 'Production Output'), ('SALES_ISS', 'Sales Issue'), ('SALES_RET', 'Sales Return'), ('PURC_RET', 'Purchase Return'), ('ADJ_POS', 'Stock Adjustment Positive'), ('ADJ_NEG', 'Stock Adjustment Negative')], max_length=20)),
                ('qty_in', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('qty_out', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='inventory.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
