# Generated by Django 5.0.14 on 2026-03-19 07:15

from django.db import migrations

def create_opening_stock(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    StockLedger = apps.get_model('inventory', 'StockLedger')
    
    products = Product.objects.filter(current_stock__gt=0)
    ledgers = []
    for product in products:
        ledgers.append(
            StockLedger(
                product=product,
                tx_type='OPENING',
                qty_in=product.current_stock,
                qty_out=0,
                reference_type='SYS',
                reference_number='OP-STOCK-MIG',
                remarks='Initial stack migration'
            )
        )
    if ledgers:
        StockLedger.objects.bulk_create(ledgers)

def reverse_stock(apps, schema_editor):
    StockLedger = apps.get_model('inventory', 'StockLedger')
    StockLedger.objects.filter(tx_type='OPENING', reference_number='OP-STOCK-MIG').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_allow_negative_stock_product_inventory_class_and_more'),
    ]

    operations = [
        migrations.RunPython(create_opening_stock, reverse_stock),
    ]
