# Generated by Django 5.0.14 on 2026-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_salestarget_category'),
        ('inventory', '0006_stockadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Everbolt', 'Everbolt'), ('Everleaf', 'Everleaf')], default='Everbolt', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Confectionery', 'Confectionery'), ('Dried Fruits', 'Dried Fruits'), ('Dried Vegetables', 'Dried Vegetables'), ('Spices', 'Spices'), ('Tea', 'Tea'), ('Kithul', 'Kithul')], default='Confectionery', max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='tea_type',
            field=models.CharField(blank=True, choices=[('Herbal Tea', 'Herbal Tea'), ('Artisan Tea', 'Artisan Tea'), ('Flavored Tea', 'Flavored Tea'), ('Black Tea', 'Black Tea'), ('Green Tea', 'Green Tea'), ('Catering Tea', 'Catering Tea')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Direct Packing', 'Direct Packing'), ('Blended Tea Products', 'Blended Tea Products'), ('Confectionery Packing', 'Confectionery Packing'), ('Repacking', 'Repacking'), ('Trading Products', 'Trading Products')], default='Direct Packing', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('pcs', 'pcs'), ('box', 'box'), ('pack', 'pack'), ('Kg', 'Kg'), ('g', 'g'), ('ml', 'ml'), ('l', 'l')], default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_unit',
            field=models.CharField(choices=[('pcs', 'pcs'), ('box', 'box'), ('pack', 'pack'), ('Kg', 'Kg'), ('g', 'g'), ('ml', 'ml'), ('l', 'l')], default='pcs', max_length=20),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
