# Generated by Django 5.0.14 on 2026-04-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_special_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_tier_100',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for <= 100 pcs', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_tier_250',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for <= 250 pcs', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_tier_500',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for >= 500 pcs', max_digits=12, null=True),
        ),
    ]
