# Generated by Django 5.0.14 on 2026-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockreserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Direct Packing', 'Direct Packing'), ('Blended Tea Products', 'Blended Tea Products'), ('Confectionery Packing', 'Confectionery Packing'), ('Repacking', 'Repacking'), ('Trading Products', 'Trading Products')], default='Direct Packing', max_length=50, verbose_name='Production Type'),
        ),
    ]
