# Generated by Django 5.0.14 on 2026-05-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_load_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_tier_100',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Price for <= 100 pcs', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_tier_250',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Price for <= 250 pcs', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_tier_500',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Price for >= 500 pcs', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
