# Generated by Django 5.0.14 on 2026-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_custom_load_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Everbolt', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Confectionery', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='Direct Packing', max_length=50, verbose_name='Production Type'),
        ),
    ]
