# Generated by Django 5.0.14 on 2026-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_notified',
            field=models.BooleanField(default=False, help_text='True if a low-stock notification has already been sent'),
        ),
    ]
