# Generated by Django 5.0.14 on 2026-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_reorder_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_weight_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Weight of 1 Unit/Pcs in kg (e.g., 100g = 0.1)', max_digits=10),
        ),
    ]
