# Generated by Django 5.0.14 on 2026-07-13 05:05

from django.db import migrations


def migrate_static_tiers_to_dynamic(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    ProductPriceTier = apps.get_model('inventory', 'ProductPriceTier')
    
    for product in Product.objects.all():
        # The old UI assumed:
        # <= 100 pcs was price_tier_100, which actually implies 1 to 100 (so min_qty = 1)
        # <= 250 pcs was price_tier_250, implying 101 to 250 (so min_qty = 101)
        # >= 500 pcs was price_tier_500, implying 251+ or 500+ (so min_qty = 251 or 500. Let's use 251 since that's what order_generator used).
        
        # Actually, let's use the min bounds used in the old `sales.views.order_generator` for consistency:
        # price_tier_100 => min: 1
        # price_tier_250 => min: 101 (if 100 exists) else 1
        # price_tier_500 => min: 251 (if 250 exists) else (101 if 100 exists else 1)
        
        if product.price_tier_100:
            ProductPriceTier.objects.create(product=product, min_quantity=1, price=product.price_tier_100)
            
        if product.price_tier_250:
            min_q = 101 if product.price_tier_100 else 1
            ProductPriceTier.objects.create(product=product, min_quantity=min_q, price=product.price_tier_250)
            
        if product.price_tier_500:
            min_q = 251 if product.price_tier_250 else (101 if product.price_tier_100 else 1)
            ProductPriceTier.objects.create(product=product, min_quantity=min_q, price=product.price_tier_500)

def reverse_migrate_tiers(apps, schema_editor):
    ProductPriceTier = apps.get_model('inventory', 'ProductPriceTier')
    ProductPriceTier.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_add_product_price_tier'),
    ]

    operations = [
        migrations.RunPython(migrate_static_tiers_to_dynamic, reverse_migrate_tiers)
    ]
