# Generated by Django 5.0.14 on 2026-07-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_migrate_price_tiers_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_tier_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_tier_250',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_tier_500',
        ),
    ]
