# Generated by Django 5.0.14 on 2026-06-15 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_reorder_notified'),
        ('manufacturing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlanningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_production_plans', 'Can manage production plans'), ('submit_production_plans', 'Can submit production plans'), ('receive_production_notifications', 'Receives production plan email notifications')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DailyProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_plans', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_production_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('target_qty', models.IntegerField(default=0)),
                ('raw_material_qty', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('actual_used_qty', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('wastage_qty', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('actual_completed_qty', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.dailyproductionplan')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_usages', to='inventory.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_productions', to='inventory.product')),
            ],
        ),
    ]
