# Generated by Django 5.0.14 on 2026-06-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_productionplanningmodule_dailyproductionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductionplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('MORNING_SUBMITTED', 'Morning Submitted'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
    ]
