# Generated by Django 5.0.14 on 2026-07-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_alter_dailyproductionplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplanline',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplanline',
            name='pm_wastage_qty',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionplanline',
            name='pm_wastage_unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='productionplanline',
            name='rm_wastage_unit',
            field=models.CharField(default='g', max_length=20),
        ),
    ]
