# Generated by Django 5.0.14 on 2026-07-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_productionplanline_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplanline',
            name='wastage_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
