# Generated by Django 5.0.14 on 2026-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('customer_type', models.CharField(choices=[('HOTELS', 'Hotels'), ('VILLAS', 'Villas'), ('APARTMENTS', 'Apartments'), ('CAFES', 'Cafes'), ('RESTAURANTS', 'Restaurants'), ('SUPERMARKETS', 'Supermarkets'), ('DISTRIBUTORS', 'Distributors / Wholesalers'), ('EXPORTS', 'Exports'), ('CORPORATE', 'Corporate'), ('HOSPITALS', 'Hospitals'), ('ACADEMIC', 'Academic Institutions'), ('BANKS', 'Banks')], max_length=50)),
                ('area_route', models.CharField(max_length=150)),
                ('payment_terms', models.CharField(choices=[('CASH', 'Cash'), ('COD', 'COD'), ('CREDIT_15', 'Credit - 15 days'), ('CREDIT_30', 'Credit - 30 days'), ('CREDIT_45', 'Credit - 45 days'), ('CREDIT_60', 'Credit - 60 days')], default='CASH', max_length=50)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('vat_enabled', models.BooleanField(default=True, help_text='Always compute 18% VAT')),
            ],
        ),
    ]
