# Generated by Django 5.0.14 on 2026-03-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
