# Generated by Django 5.0.14 on 2026-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_credit_limit_customer_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
