# Generated by Django 5.0.14 on 2026-03-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_nic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='area_route',
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_customer_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLACKLIST', 'Blacklist'), ('ONHOLD', 'On Hold')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_type',
            field=models.CharField(blank=True, choices=[('CAMPAIGN', 'Campaign'), ('DIRECT_CONTACT', 'Direct Contact'), ('SHOWROOM', 'Showroom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('DIRECT_DEPOSIT', 'Direct Deposit')], default='CASH', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='special_price_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('HOTELS', 'Hotels'), ('VILLAS', 'Villas'), ('APARTMENTS', 'Apartments'), ('CAFES', 'Cafes'), ('RESTAURANTS', 'Restaurants'), ('SUPERMARKETS', 'Supermarkets'), ('DISTRIBUTORS', 'Distributors / Wholesalers'), ('EXPORTS', 'Exports'), ('CORPORATE', 'Corporate'), ('HOSPITALS', 'Hospitals'), ('ACADEMIC', 'Academic Institutions'), ('BANKS', 'Banks'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(choices=[('CASH', 'Cash'), ('COD', 'COD'), ('CREDIT_7', 'Credit - 7 days'), ('CREDIT_15', 'Credit - 15 days'), ('CREDIT_30', 'Credit - 30 days'), ('CREDIT_45', 'Credit - 45 days'), ('CREDIT_60', 'Credit - 60 days')], default='CASH', max_length=50),
        ),
    ]
