# Generated by Django 5.0.14 on 2026-03-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_nic_customer_billing_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_province',
            field=models.CharField(blank=True, choices=[('WESTERN', 'Western Province'), ('CENTRAL', 'Central Province'), ('SOUTHERN', 'Southern Province'), ('UVA', 'Uva Province'), ('SABARAGAMUWA', 'Sabaragamuwa Province'), ('NORTH_WESTERN', 'North Western Province'), ('NORTH_CENTRAL', 'North Central Province'), ('NORTHERN', 'Northern Province'), ('EASTERN', 'Eastern Province')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_province',
            field=models.CharField(blank=True, choices=[('WESTERN', 'Western Province'), ('CENTRAL', 'Central Province'), ('SOUTHERN', 'Southern Province'), ('UVA', 'Uva Province'), ('SABARAGAMUWA', 'Sabaragamuwa Province'), ('NORTH_WESTERN', 'North Western Province'), ('NORTH_CENTRAL', 'North Central Province'), ('NORTHERN', 'Northern Province'), ('EASTERN', 'Eastern Province')], max_length=100, null=True),
        ),
    ]
