# Generated by Django 5.0.14 on 2026-04-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_customer_assigned_sales_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
