# Generated by Django 5.0.14 on 2026-05-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_customer_phone_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
