# Generated by Django 5.0.14 on 2026-06-01 07:13

from django.db import migrations


def migrate_legacy_addresses(apps, schema_editor):
    Customer = apps.get_model('crm', 'Customer')
    CustomerDeliveryAddress = apps.get_model('crm', 'CustomerDeliveryAddress')
    
    for customer in Customer.objects.all():
        if customer.delivery_address_line1 or customer.delivery_city:
            if not CustomerDeliveryAddress.objects.filter(customer=customer).exists():
                CustomerDeliveryAddress.objects.create(
                    customer=customer,
                    label='Primary Address',
                    line1=customer.delivery_address_line1,
                    line2=customer.delivery_address_line2,
                    city=customer.delivery_city,
                    province=customer.delivery_province,
                    zip_code=customer.delivery_zip_code,
                    is_default=True
                )

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_customerdeliveryaddress'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_addresses, reverse_code=migrations.RunPython.noop),
    ]
