# Generated by Django 5.0.14 on 2026-09-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_migrate_legacy_delivery_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('edit_credit_limit', 'Can edit customer credit limits'), ('edit_payment_terms', 'Can edit customer payment terms')]},
        ),
    ]
