# Generated by Django 5.0.14 on 2026-09-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('edit_credit_limit_customer', 'Can edit customer credit limits'), ('edit_payment_terms_customer', 'Can edit customer payment terms')]},
        ),
    ]
