# Generated by Django 5.0.14 on 2026-07-14 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ISO Category',
                'verbose_name_plural': 'ISO Categories',
            },
        ),
        migrations.CreateModel(
            name='ISOCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_type', models.CharField(choices=[('DAILY', 'Daily'), ('TWO_WEEKS', '2 Weeks'), ('CUSTOM', 'Custom')], default='DAILY', max_length=20)),
                ('custom_duration_days', models.PositiveIntegerField(blank=True, help_text='Number of days if duration is custom', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='iso.isocategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISO Criteria',
                'verbose_name_plural': 'ISO Criteria',
                'permissions': [('can_manage_iso', 'Can manage ISO checklists')],
            },
        ),
        migrations.CreateModel(
            name='ISOCriteriaTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='iso.isocriteria')),
            ],
            options={
                'verbose_name': 'ISO Task Template',
                'verbose_name_plural': 'ISO Task Templates',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ISODailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='iso.isocriteria')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISO Daily Plan',
                'verbose_name_plural': 'ISO Daily Plans',
                'unique_together': {('criteria', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ISODailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=500)),
                ('is_checked', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='iso.isodailyplan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_tasks', to='iso.isocriteriatasktemplate')),
            ],
            options={
                'verbose_name': 'ISO Daily Task',
                'verbose_name_plural': 'ISO Daily Tasks',
            },
        ),
    ]
