# Generated by Django 5.0.14 on 2026-07-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isodailytask',
            name='template',
        ),
        migrations.DeleteModel(
            name='ISOCriteriaTaskTemplate',
        ),
    ]
