# Generated by Django 5.0.14 on 2026-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso', '0002_remove_isodailytask_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isodailytask',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='isodailytask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=10),
        ),
    ]
