# Generated by Django 5.0.14 on 2026-07-15 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso', '0003_remove_isodailytask_is_checked_isodailytask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='isodailyplan',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='isodailyplan',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='iso.isocriteria'),
        ),
        migrations.AlterField(
            model_name='isodailyplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
