# Generated by Django 5.0.14 on 2026-03-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
