# Generated by Django 5.0.14 on 2026-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoice_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
