# Generated by Django 5.0.14 on 2026-04-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_invoice_designated_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
