# Generated by Django 5.0.14 on 2026-04-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_invoice_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Customer'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to Invoice'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='return',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
