# Generated by Django 5.0.14 on 2026-04-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reviewer_notes',
            field=models.TextField(blank=True, help_text='Notes from the approver/manager', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
