# Generated by Django 5.0.14 on 2026-04-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_invoice_reviewer_notes_quotation_is_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVAL_PENDING', 'Pending Approval'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCEL_PENDING', 'Cancellation Pending'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
