# Generated by Django 5.0.14 on 2026-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_invoice_cancellation_reason_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
