# Generated by Django 5.0.14 on 2026-04-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_invoice_total_discount_invoiceitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
