# Generated by Django 5.0.14 on 2026-04-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_quotation_total_discount_quotationitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVAL_PENDING', 'Pending Approval'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('EDIT_PENDING', 'Edit Pending'), ('CANCEL_PENDING', 'Cancellation Pending'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
