# Generated by Django 5.0.14 on 2026-04-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_product_type'),
        ('sales', '0014_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('delivery_address', models.TextField()),
                ('delivery_date', models.DateField()),
                ('delivered_by', models.CharField(choices=[('SUMITH', 'Sumith'), ('ASANGA', 'Asanga'), ('CHAMINDA', 'Chaminda'), ('KESHAN', 'Keshan'), ('MANISTHA', 'Manistha'), ('OTHER', 'Other')], max_length=50)),
                ('other_delivery_person', models.CharField(blank=True, help_text="Fill if 'Other' is selected", max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='sales.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.deliverynote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
