# Generated by Django 5.0.14 on 2026-05-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_deliverynote_deliverynoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_discount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_discount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='discount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='line_total',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
