# Generated by Django 5.0.14 on 2026-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_invoice_tax_amount_alter_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_discount_type',
            field=models.CharField(choices=[('AMOUNT', 'Amount'), ('PERCENT', 'Percentage')], default='AMOUNT', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='custom_discount_value',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='custom_discount_type',
            field=models.CharField(choices=[('AMOUNT', 'Amount'), ('PERCENT', 'Percentage')], default='AMOUNT', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='custom_discount_value',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
    ]
