# Generated by Django 5.0.14 on 2026-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_invoice_custom_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_type',
            field=models.CharField(choices=[('AMOUNT', 'Amount'), ('PERCENT', 'Percentage')], default='AMOUNT', max_length=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount_type',
            field=models.CharField(choices=[('AMOUNT', 'Amount'), ('PERCENT', 'Percentage')], default='AMOUNT', max_length=10),
        ),
    ]
