# Generated by Django 5.0.14 on 2026-05-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_custom_load_price_and_more'),
        ('sales', '0018_invoiceitem_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='custom_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
