# Generated by Django 5.0.14 on 2026-05-13 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_customer_nic'),
        ('inventory', '0013_alter_product_brand_alter_product_category_and_more'),
        ('sales', '0020_remove_deliverynote_other_delivery_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='Price per unit at time of return (used for credit note value)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='return',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.invoice'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=5, max_digits=12)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('return_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='sales.return')),
            ],
        ),
    ]
