# Generated by Django 5.0.14 on 2026-05-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_add_creditnote_update_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteitem',
            name='invoiced_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Original invoiced quantity — used to cap delivery and track partial delivery'),
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Actual quantity delivered in this DN'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('COD', 'Cash On Delivery'), ('CREDIT', 'Credit Invoice')], default='CREDIT', max_length=20),
        ),
    ]
