# Generated by Django 5.0.14 on 2026-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_add_cash_invoice_type_dn_invoiced_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='Amount before tax and rounding', max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='Amount before tax and rounding', max_digits=12),
        ),
    ]
