# Generated by Django 5.0.14 on 2026-05-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_invoice_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('CASH', 'Cash Invoice'), ('COD', 'Cash On Delivery'), ('CREDIT', 'Credit Invoice')], default='CASH', max_length=20),
        ),
    ]
