# Generated by Django 5.0.14 on 2026-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='snap_delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snap_delivery_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snap_delivery_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snap_delivery_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snap_delivery_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
