# Generated by Django 5.0.14 on 2026-06-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_invoice_snap_delivery_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
