# Generated by Django 5.0.14 on 2026-06-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_brand_alter_product_category_and_more'),
        ('sales', '0028_quotation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='product',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='return',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='return',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='return',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='return',
            name='returned_product',
        ),
        migrations.RemoveField(
            model_name='return',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=5, max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.creditnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=12)),
                ('reason', models.CharField(choices=[('DAMAGED_PACK', 'Damaged Pack'), ('WRONG_ITEM', 'Wrong Item'), ('NEAR_EXPIRY', 'Near Expiry'), ('QUALITY', 'Quality Complaint')], max_length=50)),
                ('condition', models.CharField(choices=[('SELLABLE', 'Good / Sellable'), ('DAMAGED', 'Damaged / Unsellable')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.return')),
            ],
        ),
    ]
