# Generated by Django 5.0.14 on 2026-06-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_remove_creditnote_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'permissions': [('change_dn_status', 'Can change delivery note status')]},
        ),
    ]
