# Generated by Django 5.0.14 on 2026-09-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_creditnote_designated_approver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditnote',
            options={'permissions': [('approve_creditnote', 'Can approve credit notes')]},
        ),
    ]
